In [36]:
import numpy as np
import pandas as pd
from datetime import datetime

In [37]:
df_fight_stats = pd.read_csv('/home/duyle/Documents/VSC/Project_DAP391/og_dataset/ufc_fight_stats.csv')
df_ufc_fighter_tott = pd.read_csv('/home/duyle/Documents/VSC/Project_DAP391/og_dataset/ufc_fighter_tott.csv')

In [38]:
df_fight_stats[df_fight_stats['EVENT']== 'ufc - ultimate brazil']

Empty DataFrame
Columns: [EVENT, BOUT, ROUND, FIGHTER, KD, SIG.STR., SIG.STR. %, TOTAL STR., TD, TD %, SUB.ATT, REV., CTRL, HEAD, BODY, LEG, DISTANCE, CLINCH, GROUND]
Index: []

In [39]:
df_fight_stats['EVENT'] = df_fight_stats['EVENT'].str.strip().str.lower()
df_fight_stats['BOUT'] = df_fight_stats['BOUT'].str.strip().str.lower()
df_fight_stats['FIGHTER'] = df_fight_stats['FIGHTER'].str.strip().str.lower()

In [40]:
df_fight_stats

,EVENT,BOUT,ROUND,FIGHTER,KD,SIG.STR.,SIG.STR. %,TOTAL STR.,TD,TD %,SUB.ATT,REV.,CTRL,HEAD,BODY,LEG,DISTANCE,CLINCH,GROUND
0,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 1,colby covington,0.0,10 of 51,19%,10 of 51,0 of 2,0%,0.0,0.0,0:22,5 of 42,4 of 6,1 of 3,10 of 51,0 of 0,0 of 0
1,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 2,colby covington,0.0,19 of 50,38%,25 of 56,1 of 3,33%,0.0,0.0,1:28,13 of 43,4 of 5,2 of 2,17 of 48,0 of 0,2 of 2
2,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 3,colby covington,0.0,8 of 23,34%,36 of 54,0 of 3,0%,0.0,0.0,1:50,8 of 23,0 of 0,0 of 0,6 of 21,0 of 0,2 of 2
3,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 1,joaquin buckley,0.0,23 of 55,41%,23 of 55,0 of 0,---,0.0,0.0,0:09,18 of 47,4 of 7,1 of 1,20 of 49,1 of 2,2 of 4
4,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 2,joaquin buckley,0.0,28 of 55,50%,29 of 56,0 of 1,0%,0.0,0.0,0:01,20 of 46,6 of 7,2 of 2,24 of 50,4 of 5,0 of 0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37297,ufc 2: no way out,johnny rhodes vs. david levicki,Round 1,david levicki,0.0,4 of 5,80%,95 of 102,0 of 0,---,0.0,0.0,--,4 of 5,0 of 0,0 of 0,1 of 2,2 of 2,1 of 1
37298,ufc 2: no way out,patrick smith vs. ray wizard,Round 1,patrick smith,0.0,1 of 1,100%,1 of 1,0 of 1,0%,1.0,0.0,--,0 of 0,1 of 1,0 of 0,0 of 0,1 of 1,0 of 0
37299,ufc 2: no way out,patrick smith vs. ray wizard,Round 1,ray wizard,0.0,1 of 1,100%,2 of 2,0 of 0,---,0.0,0.0,--,0 of 0,0 of 0,1 of 1,1 of 1,0 of 0,0 of 0
37300,ufc 2: no way out,scott morris vs. sean daugherty,Round 1,scott morris,0.0,1 of 1,100%,2 of 2,1 of 1,100%,1.0,0.0,--,1 of 1,0 of 0,0 of 0,0 of 0,1 of 1,0 of 0
37301,ufc 2: no way out,scott morris vs. sean daugherty,Round 1,sean daugherty,0.0,0 of 4,0%,1 of 5,0 of 0,---,0.0,0.0,--,0 of 2,0 of 0,0 of 2,0 of 3,0 of 1,0 of 0

In [41]:
df_fight_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37302 entries, 0 to 37301
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EVENT       37302 non-null  object
 1   BOUT        37302 non-null  object
 2   ROUND       37260 non-null  object
 3   FIGHTER     37260 non-null  object
 4   KD          37260 non-null  float64
 5   SIG.STR.    37260 non-null  object
 6   SIG.STR. %  37260 non-null  object
 7   TOTAL STR.  37260 non-null  object
 8   TD          37260 non-null  object
 9   TD %        37260 non-null  object
 10  SUB.ATT     37260 non-null  float64
 11  REV.        37260 non-null  float64
 12  CTRL        37260 non-null  object
 13  HEAD        37260 non-null  object
 14  BODY        37260 non-null  object
 15  LEG         37260 non-null  object
 16  DISTANCE    37260 non-null  object
 17  CLINCH      37260 non-null  object
 18  GROUND      37260 non-null  object
dtypes: float64(3), object(16)
memory usage: 5.4+ MB

In [42]:
def split_function(df, col_name, attempt_col, land_col):
    df[land_col] = None
    df[attempt_col] = None

    valid_rows = df[col_name].str.contains(r"^\d+ of \d+$", na = False)
    valid_data = df.loc[valid_rows,col_name].str.split(" of ", expand=True)

    df.loc[valid_rows, land_col] = pd.to_numeric(valid_data[0], errors = 'raise')
    df.loc[valid_rows, attempt_col] = pd.to_numeric(valid_data[1], errors = 'raise')

    invalid_rows = ~valid_rows
    if invalid_rows.any():
        print(invalid_rows.sum())
    return df

def cv_time(time):
    if isinstance(time, str):
        parts = time.split(':')
        if len(parts) == 2:
            minutes, seconds = parts
            if minutes.isdigit() and seconds.isdigit():
                return int(minutes) * 60 + int(seconds)
    return None

In [43]:
df_fight_stats = split_function(df_fight_stats, "SIG.STR.", "sig_str_land", "sig_str_attempt")
df_fight_stats = split_function(df_fight_stats, "TOTAL STR.", "total_str_land", "total_str_attempt")
df_fight_stats = split_function(df_fight_stats, "TD", "takedown_land", "touchdown_attempt")
df_fight_stats = split_function(df_fight_stats, "LEG", "total_leg_land", "total_leg_attempt")
df_fight_stats = split_function(df_fight_stats, "DISTANCE", "total_distance_strike_land", "total_distance_strike_attempt")
df_fight_stats = split_function(df_fight_stats, "BODY", "total_body_land", "total_body_attempt")
df_fight_stats = split_function(df_fight_stats, "CLINCH", "total_clinch_land", "total_clinch_attempt")
df_fight_stats = split_function(df_fight_stats, "GROUND", "total_ground_land", "total_ground_attempt")
df_fight_stats = split_function(df_fight_stats, "HEAD", "total_head_land", "total_head_attempt")

42
42
42
42
42
42
42
42
42

In [44]:
df_fight_stats= df_fight_stats.drop(columns=['SIG.STR.','TOTAL STR.', 'TD', 'LEG', 'DISTANCE', 'BODY', 'CLINCH', 'GROUND', 'HEAD'])

In [45]:
df_fight_stats['CTRL'] = df_fight_stats['CTRL'].apply(cv_time)

In [46]:
df_fight_stats['TD %'] = df_fight_stats['TD %'].replace('---', 0).str.replace('%', '', regex=True).astype(float) / 100
df_fight_stats['SIG.STR. %'] = df_fight_stats['SIG.STR. %'].replace('---', 0).str.replace('%', '', regex=True).astype(float) / 100

In [47]:
df_fight_stats['TD %'] = df_fight_stats['TD %'].fillna(0)
df_fight_stats['SIG.STR. %'] = df_fight_stats['SIG.STR. %'].fillna(0)
df_fight_stats['CTRL'] = df_fight_stats['CTRL'].fillna(0)

In [48]:
df_fight_stats[df_fight_stats['EVENT']== 'ufc - ultimate brazil']

,EVENT,BOUT,ROUND,FIGHTER,KD,SIG.STR. %,TD %,SUB.ATT,REV.,CTRL,...,total_distance_strike_attempt,total_distance_strike_land,total_body_attempt,total_body_land,total_clinch_attempt,total_clinch_land,total_ground_attempt,total_ground_land,total_head_attempt,total_head_land
36894,ufc - ultimate brazil,frank shamrock vs. john lober,Round 1,frank shamrock,2.0,0.69,0.00,4.0,2.0,0.0,...,8,12,8,10,7,10,8,11,5,12
36895,ufc - ultimate brazil,frank shamrock vs. john lober,Round 1,john lober,0.0,0.36,0.75,1.0,0.0,0.0,...,1,8,0,0,0,0,3,3,3,10
36896,ufc - ultimate brazil,vitor belfort vs. wanderlei silva,Round 1,vitor belfort,1.0,0.53,0.00,0.0,0.0,0.0,...,7,13,0,0,0,0,0,0,7,13
36897,ufc - ultimate brazil,vitor belfort vs. wanderlei silva,Round 1,wanderlei silva,0.0,0.50,0.00,0.0,0.0,0.0,...,1,2,0,0,0,0,0,0,0,0
36898,ufc - ultimate brazil,pedro rizzo vs. david abbott,Round 1,pedro rizzo,2.0,0.68,0.00,0.0,0.0,0.0,...,17,22,0,0,4,7,3,6,12,22
36899,ufc - ultimate brazil,pedro rizzo vs. david abbott,Round 1,david abbott,0.0,0.33,0.50,0.0,0.0,0.0,...,7,25,0,0,4,14,5,9,16,48
36900,ufc - ultimate brazil,pat miletich vs. mikey burnett,Round 1,pat miletich,0.0,0.54,0.14,0.0,0.0,0.0,...,3,11,8,10,10,13,0,0,0,6
36901,ufc - ultimate brazil,pat miletich vs. mikey burnett,Round 2,pat miletich,0.0,1.00,0.00,0.0,0.0,0.0,...,0,0,2,2,2,2,0,0,0,0
36902,ufc - ultimate brazil,pat miletich vs. mikey burnett,Round 3,pat miletich,0.0,0.50,0.00,0.0,0.0,0.0,...,1,3,2,2,3,5,0,0,2,6
36903,ufc - ultimate brazil,pat miletich vs. mikey burnett,Round 1,mikey burnett,0.0,0.42,1.00,2.0,1.0,0.0,...,0,8,8,8,9,12,0,1,0,12
36904,ufc - ultimate brazil,pat miletich vs. mikey burnett,Round 2,mikey burnett,0.0,0.66,0.00,0.0,0.0,0.0,...,0,2,4,4,4,4,0,0,0,2
36905,ufc - ultimate brazil,pat miletich vs. mikey burnett,Round 3,mikey burnett,0.0,0.68,1.00,0.0,0.0,0.0,...,1,2,8,9,10,13,0,1,2,6
36906,ufc - ultimate brazil,tsuyoshi kohsaka vs. pete williams,Round 1,tsuyoshi kohsaka,0.0,0.35,0.50,4.0,1.0,0.0,...,7,20,1,2,0,0,0,0,4,14
36907,ufc - ultimate brazil,tsuyoshi kohsaka vs. pete williams,Round 2,tsuyoshi kohsaka,0.0,0.35,1.00,1.0,0.0,0.0,...,4,16,3,3,0,1,3,3,3,15
36908,ufc - ultimate brazil,tsuyoshi kohsaka vs. pete williams,Round 1,pete williams,0.0,0.18,0.00,0.0,0.0,0.0,...,6,36,3,8,1,2,0,0,4,29
36909,ufc - ultimate brazil,tsuyoshi kohsaka vs. pete williams,Round 2,pete williams,0.0,0.20,0.00,0.0,0.0,0.0,...,6,28,4,5,0,0,0,1,2,23
36910,ufc - ultimate brazil,ebenezer fontes braga vs. jeremy horn,Round 1,ebenezer fontes braga,0.0,0.56,1.00,1.0,0.0,0.0,...,2,2,1,3,5,10,2,4,6,11
36911,ufc - ultimate brazil,ebenezer fontes braga vs. jeremy horn,Round 1,jeremy horn,0.0,0.60,0.00,0.0,0.0,0.0,...,0,0,3,4,3,5,0,0,0,1
36912,ufc - ultimate brazil,tulio palhares vs. adriano santos,Round 1,tulio palhares,0.0,0.70,1.00,0.0,0.0,0.0,...,11,23,1,1,1,1,19,20,26,36
36913,ufc - ultimate brazil,tulio palhares vs. adriano santos,Round 1,adriano santos,0.0,0.30,0.66,0.0,1.0,0.0,...,4,24,2,3,0,0,7,12,8,30
36914,ufc - ultimate brazil,cesar marscucci vs. paulo santos,NaN,NaN,NaN,0.00,0.00,NaN,NaN,0.0,...,None,None,None,None,None,None,None,None,None,None
36915,ufc - ultimate brazil,cesar marscucci vs. paulo santos,NaN,NaN,NaN,0.00,0.00,NaN,NaN,0.0,...,None,None,None,None,None,None,None,None,None,None

In [49]:
check = df_fight_stats[df_fight_stats['FIGHTER'].isnull()]

In [51]:
check['EVENT'].unique()

array(['ufc - ultimate brazil', 'ufc 17: redemption',
       'ufc 16: battle in the bayou', 'ufc 12: judgement day',
       "ufc - ultimate ultimate '96", 'ufc 11: the proving ground',
       'ufc 10: the tournament', 'ufc 8: david vs goliath',
       "ufc - ultimate ultimate '95", 'ufc 7: the brawl in buffalo',
       'ufc 6: clash of the titans', 'ufc 4: revenge of the warriors'],
      dtype=object)

In [52]:

       
events_to_remove = [
    "ufc - ultimate ultimate '96",
    "ufc 10: the tournament",
    "ufc 9: motor city madness",
    "ufc 8: david vs goliath",
    "ufc - ultimate ultimate '95",
    "ufc 7: the brawl in buffalo",
    "ufc 6: clash of the titans",
    "ufc 5: the return of the beast",
    "ufc 4: revenge of the warriors",
    "ufc 3: the american dream",
    "ufc 2: no way out",
    'ufc - ultimate brazil', 'ufc 17: redemption',
       'ufc 16: battle in the bayou', 'ufc 12: judgement day',
       "ufc - ultimate ultimate '96", 'ufc 11: the proving ground',
]

# Remove rows where 'EVENT' matches the specified values
df_fight_stats = df_fight_stats[~df_fight_stats['EVENT'].isin(events_to_remove)]

In [53]:
df_fight_stats.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36974 entries, 0 to 37041
Data columns (total 28 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   EVENT                          36974 non-null  object
 1   BOUT                           36974 non-null  object
 2   ROUND                          36974 non-null  object
 3   FIGHTER                        36974 non-null  object
 4   KD                             36974 non-null  float64
 5   SIG.STR. %                     36974 non-null  float64
 6   TD %                           36974 non-null  float64
 7   SUB.ATT                        36974 non-null  float64
 8   REV.                           36974 non-null  float64
 9   CTRL                           36974 non-null  float64
 10  sig_str_attempt                36974 non-null  object
 11  sig_str_land                   36974 non-null  object
 12  total_str_attempt              36974 non-null  object
 13  total_str_land                 36974 non-null  object
 14  touchdown_attempt              36974 non-null  object
 15  takedown_land                  36974 non-null  object
 16  total_leg_attempt              36974 non-null  object
 17  total_leg_land                 36974 non-null  object
 18  total_distance_strike_attempt  36974 non-null  object
 19  total_distance_strike_land     36974 non-null  object
 20  total_body_attempt             36974 non-null  object
 21  total_body_land                36974 non-null  object
 22  total_clinch_attempt           36974 non-null  object
 23  total_clinch_land              36974 non-null  object
 24  total_ground_attempt           36974 non-null  object
 25  total_ground_land              36974 non-null  object
 26  total_head_attempt             36974 non-null  object
 27  total_head_land                36974 non-null  object
dtypes: float64(6), object(22)
memory usage: 8.2+ MB

In [54]:
df_fight_stats.to_csv('ufc_fight_stats_processed.csv',index=False)