In [2]:
import numpy as np
import pandas as pd
from datetime import datetime

In [72]:
df_ufc_event = pd.read_csv('ufc_event_details_processed.csv')
df_fight_results = pd.read_csv('ufc_fight_results_processed_official.csv')
df_fight_stats = pd.read_csv('ufc_fight_stats_processed.csv')

## Creating summary files of names & fighters' history

In [4]:
df_fight_results['BOUT'] = df_fight_results['BOUT'].str.lower().str.strip()
df_fight_results['BOUT'] = df_fight_results['BOUT'].str.replace("  vs.", " vs.", regex=False)
df_fight_stats['BOUT'] = df_fight_stats['BOUT'].str.lower().str.strip()
df_fight_results['EVENT'] = df_fight_results['EVENT'].str.lower().str.strip()
df_fight_stats['EVENT'] = df_fight_stats['EVENT'].str.lower().str.strip()
df_ufc_event['EVENT'] = df_ufc_event['EVENT'].str.lower().str.strip()

In [5]:
def clean_bout_name(bout_name):
    return " vs. ".join(sorted(bout_name.lower().strip().replace("  ", " ").split(" vs. ")))
df_fight_stats["BOUT"] = df_fight_stats["BOUT"].apply(clean_bout_name)
df_fight_results["BOUT"] = df_fight_results["BOUT"].apply(clean_bout_name)

## Adding weightclass to the fight_stats for easier processing

In [6]:
fight_stats_with_weightclass = df_fight_stats.merge(

    df_fight_results[['EVENT', 'BOUT', 'weightclass_numeric','weight_class','gender','is_title_bout']],

    on=['EVENT', 'BOUT'],

    how='left'
)

In [158]:
missing_values_after_merge = fight_stats_with_weightclass[['weightclass_numeric', 'weight_class', 'gender', 'is_title_bout']].isnull().sum()

In [7]:
fight_stats_with_weightclass = fight_stats_with_weightclass.merge(

    df_ufc_event[['EVENT','DATE', 'LOCATION']],

    on=['EVENT'],

    how='left'
)

In [8]:
fight_results_with_locale = df_fight_results.merge(
    df_ufc_event[['EVENT','DATE',"LOCATION"]],
    on = ['EVENT'],
    how = 'left'
)

In [9]:
fight_results_with_locale.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   EVENT                       7787 non-null   object
 1   BOUT                        7787 non-null   object
 2   OUTCOME                     7787 non-null   object
 3   ROUND                       7787 non-null   int64
 4   TIME                        7787 non-null   int64
 5   TIME FORMAT                 7787 non-null   object
 6   FIGHTER_1                   7787 non-null   object
 7   FIGHTER_2                   7787 non-null   object
 8   Total_Rounds_Format         7787 non-null   float64
 9   Main_round_time_Format      7787 non-null   int64
 10  Num_overtime_rounds_Format  7708 non-null   float64
 11  Overtime_round_time_Format  7787 non-null   int64
 12  gender                      7787 non-null   int64
 13  is_title_bout               7787 non-null   int64
 14  weight_class                7787 non-null   object
 15  fighter_1_result            7787 non-null   int64
 16  fighter_2_result            7787 non-null   int64
 17  method_label                7787 non-null   int64
 18  weightclass_numeric         7787 non-null   int64
 19  DATE                        7787 non-null   object
 20  LOCATION                    7787 non-null   object
dtypes: float64(2), int64(10), object(9)
memory usage: 1.2+ MB

In [10]:
fight_stats_with_weightclass.to_csv('fight_stats_with_weghtclass_date_location.csv',index=False)

In [11]:
fight_results_with_locale.to_csv('fight_results_with_locale.csv',index=False)

In [ ]:
fighters_1 = pd.read_csv('fighters4.csv')
fighters_2 = pd.read_csv('fighters3.csv')
fighters_3 = pd.read_csv('fighters2.csv')
file_list = ['fighters4.csv', 'fighters3.csv', 'fighters2.csv']

# Initialize an empty DataFrame to store the combined data
combined_df = pd.DataFrame()

# Loop through all files and append them
for file in file_list:
    df = pd.read_csv(file)
    combined_df = pd.concat([combined_df, df], ignore_index=True)
combined_df = combined_df.drop_duplicates()

# Save the combined data to a new CSV file

In [57]:
combined_df

                    Name                                                img
0           Danny Abbadi                                                NaN
1       Nariman Abbassov  https://dmxg5wxfqgb4u.cloudfront.net/styles/at...
2            Tank Abbott                                                NaN
3       Hamdy Abdelwahab  https://dmxg5wxfqgb4u.cloudfront.net/styles/at...
4     Mansur Abdul-Malik  https://dmxg5wxfqgb4u.cloudfront.net/styles/at...
...                  ...                                                ...
3190         Farès Ziam   https://dmxg5wxfqgb4u.cloudfront.net/styles/at...
3191         James Zikic                                                NaN
3192         Cat Zingano  https://dmxg5wxfqgb4u.cloudfront.net/styles/at...
3193       Igor Zinoviev                                                NaN
3194        Allan Zuniga  https://dmxg5wxfqgb4u.cloudfront.net/styles/at...

[3130 rows x 2 columns]

In [63]:


combined_df.to_csv('combined_file.csv', index=False)

In [64]:
fighters = pd.read_csv('/home/duyle/Documents/VSC/Project_DAP391/processed_data/fighters_processed.csv')

In [65]:
fighters_w_image = fighters.merge(

    combined_df[['Name', 'img']],

    on=['Name'],

    how='left'
)

In [66]:
fighters_w_image['img'].fillna('https://res.cloudinary.com/da7h9bpnj/image/upload/v1740706726/q7aeoc2wkh12vfylaprk.png', inplace=True)

/tmp/ipykernel_2752537/4119941852.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fighters_w_image['img'].fillna('https://res.cloudinary.com/da7h9bpnj/image/upload/v1740706726/q7aeoc2wkh12vfylaprk.png', inplace=True)

In [71]:
fighters_w_image

,Name,Nickname,Weight_Class,Knockouts,Submissions,First_Round_Finishes,Striking_Accuracy,Takedown_Accuracy,Sig_Str_Attempted Total,Takedowns_Landed_Total,...,Sig_Strikes_Body_Percent,Sig_Strikes_Leg_Total,Sig_Strikes_Leg_Percent,Win_by_KO/TKO_Total,Win_by_KO/TKO_Percent,Win_by_Decision_Total,Win_by_Decision_Percent,Win_by_Submission_Total,Win_by_Submission_Percent,img
0,Danny Abbadi,"""The Assassin""",Lightweight Division,0,0,0,0.38,0.00,155,0.0,...,0.14,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,https://res.cloudinary.com/da7h9bpnj/image/upl...
1,Nariman Abbassov,NaN,Lightweight Division,0,0,0,0.20,0.00,225,0.0,...,0.18,11.0,0.24,0.0,0.00,0.0,0.00,0.0,0.00,https://dmxg5wxfqgb4u.cloudfront.net/styles/at...
2,Tank Abbott,"""Tank""",Heavyweight Division,0,0,0,0.39,0.00,31,0.0,...,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,https://res.cloudinary.com/da7h9bpnj/image/upl...
3,Hamdy Abdelwahab,"""The Hammer""",Heavyweight Division,5,0,4,0.52,0.80,197,3.0,...,0.08,18.0,0.18,5.0,1.00,0.0,0.00,0.0,0.00,https://dmxg5wxfqgb4u.cloudfront.net/styles/at...
4,Mansur Abdul-Malik,NaN,Middleweight Division,6,1,6,0.55,0.00,141,0.0,...,0.03,1.0,0.01,6.0,0.86,0.0,0.00,1.0,0.14,https://dmxg5wxfqgb4u.cloudfront.net/styles/at...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3158,James Zikic,"""The Messiah""",Light Heavyweight Division,0,0,0,0.44,0.00,66,0.0,...,0.28,1.0,0.03,0.0,0.00,0.0,0.00,0.0,0.00,https://res.cloudinary.com/da7h9bpnj/image/upl...
3159,Cat Zingano,"""Alpha""",Women's Featherweight Division,5,3,0,0.61,0.65,295,13.0,...,0.25,28.0,0.15,5.0,0.50,2.0,0.20,3.0,0.30,https://dmxg5wxfqgb4u.cloudfront.net/styles/at...
3160,Igor Zinoviev,NaN,Middleweight Division,0,0,0,0.00,0.00,0,0.0,...,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,https://res.cloudinary.com/da7h9bpnj/image/upl...
3161,Allan Zuniga,"""Tigre""",Lightweight Division,0,0,0,0.53,0.00,112,0.0,...,0.31,8.0,0.14,3.0,0.23,6.0,0.46,4.0,0.31,https://dmxg5wxfqgb4u.cloudfront.net/styles/at...
3162,Renzo Gracie,NaN,Welterweight Division,0,0,0,0.41,0.21,387,0.0,...,0.34,38.0,0.24,0.0,0.00,0.0,0.00,0.0,0.00,https://res.cloudinary.com/da7h9bpnj/image/upl...

In [67]:
fighters_w_image.to_csv('fighters_w_image_2.csv', index=False)

In [68]:
fighters.to_csv('fighters_w_image.csv',index=False)

In [ ]:
Do Tuan Minh	“The Train”	Dog Division	10	2	10	0.6	0.4	200	2	2	2	2	0.45	0	2	2	0.5	600	Viet Nam	Apr.10, 2010	15	7	1	154	0	23	0.32	190	0.6	17	0.3	67	0.5	62	0.3	78	0.15	10	0.45	10	0.5	4	0.35	https://res.cloudinary.com/da7h9bpnj/image/upload/v1740705240/ja3o1ufisq1mx4dld8ba.jpg

In [73]:
stats = pd.read_csv('/home/duyle/Documents/VSC/Project_DAP391/processed_data/fight_stats_with_weghtclass_date_location.csv')

In [74]:
stats

,EVENT,BOUT,ROUND,FIGHTER,KD,SIG.STR. %,TD %,SUB.ATT,REV.,CTRL,...,total_ground_attempt,total_ground_land,total_head_attempt,total_head_land,weightclass_numeric,weight_class,gender,is_title_bout,DATE,LOCATION
0,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 1,colby covington,0.0,0.19,0.00,0.0,0.0,22.0,...,0,0,42,5,5,welterweight,0,0,12-14-24,"tampa, florida, usa"
1,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 2,colby covington,0.0,0.38,0.33,0.0,0.0,88.0,...,2,2,43,13,5,welterweight,0,0,12-14-24,"tampa, florida, usa"
2,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 3,colby covington,0.0,0.34,0.00,0.0,0.0,110.0,...,2,2,23,8,5,welterweight,0,0,12-14-24,"tampa, florida, usa"
3,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 1,joaquin buckley,0.0,0.41,0.00,0.0,0.0,9.0,...,4,2,47,18,5,welterweight,0,0,12-14-24,"tampa, florida, usa"
4,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 2,joaquin buckley,0.0,0.50,0.00,0.0,0.0,1.0,...,0,0,46,20,5,welterweight,0,0,12-14-24,"tampa, florida, usa"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36973,ufc 13: the ultimate force,christophe leninger vs. guy mezger,Round 2,christophe leninger,0.0,0.33,0.00,0.0,0.0,0.0,...,0,0,2,1,4,lightweight,0,0,05-30-97,"augusta, georgia, usa"
36974,ufc 13: the ultimate force,jack nilson vs. saeed hosseini,Round 1,jack nilson,0.0,0.84,0.00,0.0,0.0,0.0,...,11,11,13,11,4,lightweight,0,0,05-30-97,"augusta, georgia, usa"
36975,ufc 13: the ultimate force,jack nilson vs. saeed hosseini,Round 1,saeed hosseini,0.0,0.20,0.00,1.0,0.0,0.0,...,0,0,4,0,4,lightweight,0,0,05-30-97,"augusta, georgia, usa"
36976,ufc 13: the ultimate force,tito ortiz vs. wes albritton,Round 1,tito ortiz,0.0,0.87,1.00,0.0,0.0,0.0,...,23,20,23,20,4,lightweight,0,0,05-30-97,"augusta, georgia, usa"
36977,ufc 13: the ultimate force,tito ortiz vs. wes albritton,Round 1,wes albritton,0.0,0.00,0.00,0.0,0.0,0.0,...,0,0,0,0,4,lightweight,0,0,05-30-97,"augusta, georgia, usa"